export const array1Data = [
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  'Tortor id aliquet lectus proin nibh nisl.',
  'Nec ullamcorper sit amet risus.',
  'Tortor at risus viverra adipiscing at in tellus integer.',
  'Ultricies mi eget mauris pharetra et.',
  'Vel eros donec ac odio tempor orci dapibus.',
  'Ut ornare lectus sit amet est.',
  'Quisque non tellus orci ac auctor augue.',
  'Ut porttitor leo a diam sollicitudin tempor.',
  'Tincidunt arcu non sodales neque sodales ut.',
  'Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget.',
  'Scelerisque fermentum dui faucibus in ornare.',
  'Vitae congue mauris rhoncus aenean vel elit scelerisque maupellentesque.',
  'Nisi quis eleifend quam adipiscing vitae proin sagittis.',
  'Donec ac odio tempor orci dapibus. ',
  'Sit amet nisl suscipit adipiscing bibendum. ',
  'Non diam phasellus vestibulum lorem. ',
  'Est ultricies integer quis auctor elit sed vulputate. ',
  'Et ultrices neque ornare aenean. ',
  'Tortor pretium viverra suspendisse potenti nullam. ',
];
export const array2Data = [
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ',
  'Sapien et ligula ullamcorper malesuada proin libero. ',
  'Odio ut sem nulla pharetra diam sit amet.',
  'Ullamcorper velit sed ullamcorper morbi tincidunt ornare. ',
  'Neque sodales ut etiam sit. ',
  'Enim lobortis scelerisque fermentum dui faucibus in. ',
  'Cras pulvinar mattis nunc sed blandit libero volutpat. ',
  'Amet justo donec enim diam vulputate ut pharetra sit. ',
  'Laoreet suspendisse interdum consectetur libero id. ',
  'Aliquet nibh praesent tristique magna sit amet purus. ',
  'Nunc consequat interdum varius sit. In mollis nunc sed id semper. ',
  'In fermentum posuere urna nec tincidunt praesent semper. ',
  'Donec pretium vulputate sapien nec sagittis aliquam malesuada. ',
  'Massa eget egestas purus viverra accumsan in nisl. ',
  'Sed risus ultricies tristique nulla aliquet enim tortor. ',
  'A diam sollicitudin tempor id eu nisl. ',
  'Rhoncus mattis rhoncus urna neque viverra justo nec ultrices. ',
  'Id semper risus in hendrerit gravida rutrum quisque. ',
  'Quis risus sed vulputate odio ut enim blandit volutpat maecenas. ',
];
